# Generated by Django 5.2.8 on 2025-12-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description', models.TextField()),
                ('game_id', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('rpg', 'RPG'), ('strategy', 'Strategy'), ('simulation', 'Simulation'), ('sports', 'Sports'), ('puzzle', 'Puzzle'), ('horror', 'Horror'), ('other', 'Other')], default='simulation', max_length=100)),
                ('multi_tags', models.CharField(blank=True, max_length=200)),
                ('image', models.FileField(upload_to='games/')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/main-image')),
                ('category', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('rpg', 'RPG'), ('strategy', 'Strategy'), ('simulation', 'Simulation'), ('sports', 'Sports'), ('puzzle', 'Puzzle'), ('horror', 'Horror'), ('other', 'Other')], default='simulation', max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('discount', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='main',
            name='category',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('rpg', 'RPG'), ('strategy', 'Strategy'), ('simulation', 'Simulation'), ('sports', 'Sports'), ('puzzle', 'Puzzle'), ('horror', 'Horror'), ('other', 'Other')], default='simulation', max_length=10),
        ),
    ]
