# Generated by Django 5.2.8 on 2025-12-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gamedetail_shop_alter_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
