# Generated by Django 5.2.8 on 2025-12-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_main_discount_alter_shop_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/main-image')),
                ('category', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('rpg', 'RPG'), ('strategy', 'Strategy'), ('simulation', 'Simulation'), ('sports', 'Sports'), ('puzzle', 'Puzzle'), ('horror', 'Horror'), ('other', 'Other')], default='simulation', max_length=100)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
