# Generated by Django 5.2.8 on 2025-12-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_topcategory_delete_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetail',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='main',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='topcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
