# Generated by Django 5.2.8 on 2025-12-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_gamedetail_slug_main_slug_topcategory_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedetail',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='main',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='topcategory',
            name='slug',
        ),
    ]
