# Generated by Django 5.2.8 on 2025-12-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_gamedetail_slug_remove_main_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
